- README.md
- server/db/models/index.js
- server/db/models/potions.js
- server/db/models/potions.spec.js
> Product model #13

- server/db/models/user.js
---
adding user inputs + validations, also added validations to email input
> adding validations to user names

- server/db/models/potions.js
> added price, and changed photo validation

- script/seed.js
- server/api/users.spec.js
- server/db/models/potions.js
- server/db/models/user.spec.js
---
I added Cody Pugster to the seed file, the specs for the user model to make sure all validations are correct and accurate across different files.
> updated user specs, seed file, to include first and last name of users

- server/db/models/potions.js
> changed NUMBER to FLOAT

- package-lock.json
- script/seed.js
> created potion seed

- server/db/models/index.js
- server/db/models/order.js
- server/db/models/potions.js
> created order model, order associations, + one edit to potion model

- script/seed.js
- server/db/models/address.js
- server/db/models/index.js
> Address model #23

- server/api/index.js
- server/api/potions.js
- server/api/users.js
---
Please check the express route in the created /api/potions.js file. It does show up on the localhost:8080/api/potions if you npm start.
> All products view #6

- client/app.js
- client/components/navbar.js
- client/components/product-card.js
- public/style.css
> pushing because my homepage works and no one elses does

- client/components/navbar.js
- client/components/product-card.js
- client/store/index.js
- client/store/products.js
---
created redux store for all products
> All products redux #35

- client/app.js
- client/components/all-product-view.js
- client/components/index.js
- client/components/navbar.js
- client/components/product-card.js
- client/index.js
- client/routes.js
> All product view component #36

- client/components/all-product-view.js
- client/components/product-card.js
- script/seed.js
> All products view is semi functional

- client/components/HomePage.js
- client/components/navbar.js
- public/style.css
> fixed the navbar and homepage and kept all previous code

- script/seed.spec.js
- server/db/models/index.js
- server/db/models/index.spec.js
- server/db/models/potions.js
---
completed methods & test specs for:
- add to cart
- remove from cart
- edit potion quantity in cart
- get potions in cart
- get cart total
for LOGGED IN users
> Cart vert slice db #41

- client/components/auth-form.js
- client/components/navbar.js
- client/routes.js
- client/store/user.js
- public/style.css
- server/api/users.js
- server/db/models/user.js
> got auth-sign-up form to work and to add new user to database, rewrote auth component.

- client/components/product-card.js
- client/components/single-product-view.js
> Fix quantity default

- client/components/auth-form.js
- client/components/navbar.js
- client/routes.js
- server/api/users.js
- server/auth/google.js
- server/db/models/user.js
> Fix login 46

- client/components/single-product-view.js
- client/store/products.js
- client/store/user.js
- server/api/user.js
- server/db/models/index.js
> User cart v2 #40

- client/store/index.js
> updated user state

- client/store/user.js
- server/api/user.js
> saving master

- client/components/all-product-view.js
- public/style.css
- server/api/user.js
- server/db/models/index.js
---
fixed user method to take a potion id. Was broken because we were passing it potion object.
> Fix add to cart button #40

- client/components/single-product-view.js
- server/api/user.js
> adding to cart bug fixed

- client/components/Cart.js
- client/components/single-product-view.js
- client/store/user.js
- server/api/user.js
- server/db/models/index.js
> Edit cart #8

- client/components/Cart.js
- client/components/ProductInCart.js
- public/style.css
> cart functionality progress

- client/store/cart.js
- server/api/user.js
> edited code for edit qt in cart

- client/store/cart.js
- client/store/user.js
> fixed bugs in store

- client/components/Cart.js
- client/store/cart.js
> fixed remove and refresh cart for logged in user

- client/components/Cart.js
- client/components/ProductInCart.js
- public/style.css
> Cart checkout button #40

- script/seed.js
> added potions to seed file

- client/components/Cart.js
- client/store/cart.js
- server/api/user.js
> edit buttons work for both logged in and guest users

- client/components/address.js
- server/db/models/index.js
> addresses added to db

- client/components/address.js
- client/components/checkout-page.js
- client/components/product-card.js
- public/style.css
> Css cleanup

- public/style.css
> Devi and I did some touchups in the cart

- client/components/all-product-view.js
- client/components/single-product-view.js
> fixes bug for logged in users

- client/components/Cart.js
- client/components/HomePage.js
- client/components/all-product-view.js
- client/components/auth-form.js
- client/components/checkout-page.js
- client/components/product-card.js
- client/components/user-home.js
- public/style.css
Reverts grace-shopper-codecodepuffs/grace-shopper#96
> Revert "More css"

- client/components/auth-form.js
- client/components/user-home.js
- public/style.css
> updated greeting for user home, updated css to make all fonts uniform
